app/scripts/modules/cluster/reports/services/ngmClusterBeneficiaries.js
if deleting activity start date empty string will not be passed to moment
if id and no activity start date don't init activity date defaults
=> fix(beneficiaries): dont pass no activity start date to moment

app/scripts/app/controllers/admin/controller.authentication.js, app/scripts/modules/cluster/reports/services/ngmClusterBeneficiaries.js, app/scripts/modules/cluster/reports/services/ngmClusterLists.js, app/scripts/modules/cluster/views/forms/report/beneficiaries/beneficiaries.html
Customization for NG GBVSS:
1. Necessary fields on the beneficiary.html were configured.
2. Site implementation was configured.
3. Organization spreadsheet was updated, requesting db update
4. Activities spreadsheet was updated, requesting db update.
=> System setup for GBVSS Nigeria 

app/scripts/modules/cluster/views/forms/report/beneficiaries/beneficiaries.html
A fix to hide undesired SADDs for NG GBV
=> bugfix: Set skip logic on form for GBV cluster

app/index.html, app/scripts/app/app.js
=> feat(monit): add sentry

app/index.html, app/scripts/app/app.js, app/scripts/modules/custom/app.js, app/scripts/modules/custom/dashboard/custom.dasboard.js, app/scripts/modules/custom/dashboard/custom.dashboard.admin.js, app/scripts/modules/custom/dashboard/custom.report.file.js, app/scripts/modules/custom/reports/controllers/custom.main.menu.js, app/scripts/modules/custom/reports/controllers/custom.report.lists.js, app/scripts/modules/custom/reports/controllers/custom.schedule.js, app/scripts/modules/custom/reports/forms/custom.form.report.js, app/scripts/modules/custom/reports/forms/custom.form.schedule.js, app/scripts/modules/custom/reports/services/ngmCustomBeneficiaries.js, app/scripts/modules/custom/reports/services/ngmCustomConfig.js, app/scripts/modules/custom/views/custom.main.html, app/scripts/modules/custom/views/forms/report/template-form-beneficiaries/annualworkplan20.v1.beneficiaries.html, app/scripts/modules/custom/views/forms/schedule/form.html, app/scripts/widgets/ngm-list/template/custom.list.file.html, app/scripts/widgets/ngm-list/template/custom_report.html
=> add:new config

app/scripts/modules/cluster/app.js, app/scripts/modules/cluster/dashboards/dashboard.4wprojectplan.js, app/scripts/modules/cluster/dashboards/dashboard.admin.js, app/scripts/modules/cluster/dashboards/dashboard.cluster.js, app/scripts/modules/cluster/dashboards/dashboard.dashboard4wplus.js, app/scripts/modules/cluster/dashboards/dashboard.performance.js, app/scripts/modules/cluster/lists/cluster.list.admin.js, app/scripts/modules/cluster/lists/form/list.org.form.js, app/scripts/modules/cluster/reports/controllers/cluster.beneficiaries.stock.admin.js, app/scripts/modules/cluster/reports/services/ngmClusterHelper.js
=> update list for Iraq

app/views/modals/contact.html
=> Update : contact

app/scripts/modules/cluster/dashboards/health/dashboard.health.js, app/scripts/modules/cluster/reports/forms/cluster.organization.form.stocks.list.js, app/scripts/modules/cluster/views/forms/warehouse/locations.html, app/scripts/modules/country/afghanistan/nutrition/services/ngmNutritionHelper.js
=> bugfix: from sentry

app/scripts/modules/cluster/reports/services/ngmClusterBeneficiaries.js
=> update: remove total_pwd on activity change

app/scripts/modules/cluster/reports/forms/cluster.organization.form.stock.js, app/scripts/modules/cluster/views/forms/stock/form.html, app/scripts/modules/cluster/views/forms/stock/locations.html, app/scripts/modules/cluster/views/forms/stock/stocks-reform.html
update some function 
and remove formComplete() because no one using stocks.html anymore
=> bugfix: stock form

app/index.html, app/scripts/modules/cluster/app.js, app/scripts/modules/cluster/reports/controllers/cluster.country.organization.list.js
adding organization and contact list
=> update: menu contacts

app/scripts/app/app.js, app/scripts/app/services/ngmAuthentication.js, app/scripts/modules/cluster/reports/services/ngmClusterValidation.js
Hmm this bug is weird did someone can see a report/project without register/login in?
=> bugfix on sentry:verified user and accessByrole function

app/scripts/modules/cluster/reports/forms/cluster.project.form.details.js
set it focal point to user if focal point not in the list rather than delete it
=> bugfix(import project): set it focal point to user if focal point not in the list 

app/scripts/modules/cluster/reports/forms/cluster.project.form.details.js, app/scripts/modules/cluster/views/forms/details/contact-details.html
=> update (contact detail): from xeditable to materialcss

app/scripts/app/directives/materialize.select.js
add additional functionality
attributes: watch, watch-model, watch-options="modelArray", searchable="string...", multiple
=> update materialize select directive

app/index.html, app/scripts/app/app.js, app/scripts/app/directives/materialize.select.js, app/scripts/modules/cluster/reports/forms/cluster.project.form.details.js, app/scripts/modules/cluster/views/cluster.upload.beneficiaries.stock.report.html, app/scripts/modules/cluster/views/forms/details/details.html, app/scripts/modules/cluster/views/forms/details/target-beneficiaries/target-beneficiaries.html, app/scripts/modules/cluster/views/forms/details/target-locations/CB/locations.html, app/scripts/modules/cluster/views/forms/details/target-locations/locations-reform.html, app/scripts/modules/cluster/views/forms/financials/financial-reform.html, app/scripts/modules/cluster/views/forms/report/beneficiaries/beneficiaries.html, app/scripts/modules/cluster/views/forms/report/location/add.location-reform.html, app/scripts/modules/cluster/views/forms/stock/stocks-reform.html, app/scripts/modules/cluster/views/forms/warehouse/locations.html, app/scripts/widgets/ngm-dropzone/template/default.html, app/scripts/widgets/ngm-html/template/COL/projectdonor.html, app/scripts/widgets/ngm-html/template/bgd/gfd/daily.report.forms.html, app/styles/main.css
angularjs material component that changed using materializecss and css :
-md-select
-md-select with search header
-chips
-md-tooltip change
=> change angular material to materializa

app/scripts/modules/cluster/dashboards/dashboard.admin.js, app/scripts/modules/cluster/reports/forms/cluster.upload.beneficiaries.stock.report.js, app/scripts/modules/cluster/views/forms/details/details.html, app/scripts/modules/cluster/views/forms/details/target-locations/locations-reform.html, app/scripts/modules/cluster/views/forms/report/beneficiaries/beneficiaries.html
=> bugfix: menu on dashboard admin and error info record admin

app/scripts/modules/cluster/reports/forms/cluster.organization.form.stock.js, app/scripts/modules/cluster/reports/services/ngmClusterLists.js, app/scripts/modules/cluster/views/forms/stock/stocks-reform.html, app/scripts/modules/cluster/views/forms/stock/stocks.html
Reverts drfaustusfade/ngm-reportHub#129
=> Revert "update: migrate donor to DB and new API for Donor"

app/scripts/modules/cluster/reports/services/ngmClusterBeneficiaries.js, app/scripts/modules/cluster/views/cluster.upload.beneficiaries.stock.report.html, app/scripts/modules/cluster/views/forms/details/target-beneficiaries/target-beneficiaries.html, app/scripts/modules/cluster/views/forms/report/beneficiaries/beneficiaries.html
=> update: separate unit type option for in-kind modality

app/scripts/modules/cluster/views/forms/details/target-beneficiaries/target-beneficiaries.html, app/scripts/modules/cluster/views/forms/report/beneficiaries/beneficiaries.html
NOTE: just temporary solution need to refactor later
=> update : put disabled  label on SADD  if protection cluster and beneficiary_category_type_id is person with disabilities

app/scripts/modules/cluster/views/forms/details/target-beneficiaries/target-beneficiaries.html, app/scripts/modules/cluster/views/forms/report/beneficiaries/beneficiaries.html
NB: change HH to Individual for IPA Cash
=> minor update : hide total amount on IPA activity

app/scripts/modules/cluster/views/forms/details/target-beneficiaries/target-beneficiaries.html, app/scripts/modules/cluster/views/forms/report/beneficiaries/beneficiaries.html
Miscommunication about which activity that doesn't need the total amount field
=> minor update: show total_amont only IPA Cash

app/scripts/modules/cluster/views/cluster.upload.beneficiaries.stock.report.html, app/scripts/modules/cluster/views/forms/details/target-beneficiaries/target-beneficiaries.html, app/scripts/modules/cluster/views/forms/report/beneficiaries/beneficiaries.html
For now, we hardcoded to disable thing like this
suggestion to add attribute response_enable : true/false
=> minor update : disabled covid response for ESNFI in ET

app/scripts/modules/cluster/reports/services/ngmClusterLists.js, app/scripts/modules/cluster/views/forms/stock/stocks-reform.html
=> update: new donor for ethiopia and minor update on UI

app/scripts/app/controllers/admin/controller.profile.js
Solution:
change from query parameter to body parameter
change how to send parameter for get user information
=> bugfix(profilepage): username with "&" character

app/scripts/app/controllers/admin/controller.authentication.js, app/scripts/app/services/ngmHelper.js, app/scripts/app/views/authentication/register.html, app/scripts/app/views/typeahead.html
adding helper text  (organization field) on register form
=> bugfix: register form

app/scripts/app/controllers/admin/controller.authentication.js, app/scripts/app/services/ngmHelper.js, app/scripts/app/views/authentication/register.html, app/scripts/app/views/typeahead.html
adding helper text  (organization field) on register form
=> bugfix(register): when put organization

app/scripts/app/controllers/admin/controller.authentication.js, app/scripts/app/controllers/admin/controller.profile.js, app/scripts/app/views/authentication/profile-not-found.html, app/scripts/app/views/authentication/profile.html
update
add not found profile page
add validation and notification
=> bugfix(profile): when update profile user itself

app/scripts/modules/cluster/reports/forms/cluster.project.form.details.js, app/scripts/modules/cluster/reports/forms/cluster.project.form.report.js, app/scripts/modules/cluster/reports/forms/cluster.upload.beneficiaries.stock.report.js, app/scripts/modules/cluster/reports/services/ngmClusterLists.js, app/scripts/modules/cluster/views/cluster.upload.beneficiaries.stock.report.html, app/scripts/modules/cluster/views/forms/details/target-beneficiaries/target-beneficiaries.html, app/scripts/modules/cluster/views/forms/report/beneficiaries/beneficiaries.html
migrate Beneficiarytypes to DB
=> update: migrate  Beneficiary types to DB

app/scripts/modules/cluster/dashboards/dashboard.cluster.js
=> change icon

app/scripts/app/controllers/admin/controller.authentication.js, app/scripts/app/views/authentication/register.html
=> upgrade register form

app/scripts/app/controllers/admin/controller.authentication.js, app/scripts/app/views/authentication/register.html, app/styles/ngm-form.css
=> update: register form phone number

app/scripts/app/controllers/admin/controller.authentication.js, app/scripts/app/views/authentication/register.html, app/scripts/app/views/typeahead.html, app/styles/ngm-form.css
- add helper text
- add confirm password to match password that user make
- username cannot contain white space
- password minimal character is 8 and at least have 1 Uppercase
=> upgrade(register): register form

app/scripts/app/controllers/admin/controller.team.js, app/scripts/app/views/authentication/team.html
-put a tag for pending user
-add search
=> update: team deactivated table

app/scripts/modules/cluster/reports/forms/cluster.project.form.details.js, app/scripts/modules/cluster/views/forms/details/details.html
=> update(detail): put explanation for implementing partner,programe partner

app/scripts/modules/cluster/dashboards/dashboard.admin.js, app/scripts/modules/cluster/reports/controllers/cluster.project.summary.js, app/scripts/modules/cluster/reports/forms/cluster.organization.form.stocks.list.js, app/scripts/modules/cluster/views/forms/warehouse/locations.html, app/scripts/widgets/ngm-table/templates/cluster/admin.progress.beneficiaries.html, app/scripts/widgets/ngm-table/templates/cluster/admin.project.list.html, app/styles/main.css
another update in this PR
minor-update
update: delete project request param
bug-fix: stock-location
add: validate when edit warehouse
add: checking warehouse is exists or not when adding a new warehouse
=> feature : send reminder email for report pending
